Repository wecode-bootcamp-korea/13-monawe-frontend, pull requests merged in 2020-10, with the labels that each got.

#1 [13기 김수연] Add: Navbar layout 기능 구현 / Main page story component 추가
  .eslintrc.json
  debug.log
  package-lock.json
  package.json
  public/data/list.json
  public/data/login.json
  public/data/nav.json
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/components/MonaweStory/MonaweStory.js
  src/pages/MainPage/components/MonaweStory/MonaweStory.scss
  src/pages/MainPage/components/MonaweStory/MonaweStoryData.js
  src/pages/components/Nav/MenuDropBox/ContentType.js
  src/pages/components/Nav/MenuDropBox/ContentType.scss
  src/pages/components/Nav/MenuDropBox/ListType.js
  src/pages/components/Nav/MenuDropBox/ListType.scss
  src/pages/components/Nav/MenuDropBox/MonawePet.js
  src/pages/components/Nav/MenuDropBox/MonawePet.scss
  src/pages/components/Nav/MyCurator/MyCurator.js
  src/pages/components/Nav/MyCurator/MyCurator.scss
  src/pages/components/Nav/MyCurator/components/MyCuratorSlider.js
  src/pages/components/Nav/MyCurator/components/MyCuratorSlider.scss
  src/pages/components/Nav/Nav.js
  src/pages/components/Nav/Nav.scss
  src/pages/components/Nav/Navdata.js
  src/pages/components/Nav/SearchBox/SearchBox.js
  src/pages/components/Nav/SearchBox/SearchBox.scss
Labels: Status: Accepted, Status: 수정 요청

#6 [13기 이지영] 메인페이지 product recommendation component 구현 완료
  package-lock.json
  src/Routes.js
  src/pages/DetailPage/Components/ProductInfo/Option/Options.js
  src/pages/DetailPage/Components/ProductInfo/Option/Options.scss
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.js
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.scss
  src/pages/DetailPage/DetailPage.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/components/ProductRecommendation/ProductRecommendation.js
  src/pages/MainPage/components/ProductRecommendation/ProductRecommendation.scss
Labels: Status: Accepted

#8 [13기 이지영] Feature/detail page 수정
  src/Routes.js
  src/pages/DetailPage/Components/ProductInfo/Option/Options.js
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.js
  src/pages/DetailPage/DetailPage.js
  src/pages/MainPage/MainPage.js
  src/pages/components/Nav/Nav.js
  src/pages/components/Nav/SearchBox/SearchBox.js
Labels: Status: Accepted

#5 [13기 백경민] Add: Login page complete
  debug.log
  public/data/login.json
  src/Config.js
  src/pages/JoinStep2/JoinStep2.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#9 [13기 백경민] Fix: 추가 충돌 해결 및 리팩토링
  src/Styles/common.scss
  src/index.js
  src/pages/JoinSteps/JoinStepOne.js
  src/pages/JoinSteps/JoinStepThree.js
  src/pages/JoinSteps/JoinStepTwo.js
  src/pages/JoinSteps/JoinStepTwo.scss
  src/pages/Welcome/Welcome.js
  src/pages/Welcome/Welcome.scss
Labels: Status: 수정 요청

#12 [13기 김수연] Modify: Nav/MyCurator/SearchBox -> NavContainer 통합
  src/Routes.js
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.js
  src/pages/DetailPage/DetailPage.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/components/MonaweStory/MonaweStory.js
  src/pages/MainPage/components/MonaweStory/MonaweStory.scss
  src/pages/MainPage/components/MonaweStory/MonaweStoryData.js
  src/pages/MyPage/MyPage.js
  src/pages/components/NavContainer/MyCurator/MyCurator.js
  src/pages/components/NavContainer/MyCurator/MyCurator.scss
  src/pages/components/NavContainer/MyCurator/components/MyCuratorSlider.js
  src/pages/components/NavContainer/MyCurator/components/MyCuratorSlider.scss
  src/pages/components/NavContainer/Nav/MenuDropBox/ContentType.js
  src/pages/components/NavContainer/Nav/MenuDropBox/ContentType.scss
  src/pages/components/NavContainer/Nav/MenuDropBox/ListType.js
  src/pages/components/NavContainer/Nav/MenuDropBox/ListType.scss
  src/pages/components/NavContainer/Nav/MenuDropBox/MonawePet.js
  src/pages/components/NavContainer/Nav/MenuDropBox/MonawePet.scss
  src/pages/components/NavContainer/Nav/Nav.js
  src/pages/components/NavContainer/Nav/Nav.scss
  src/pages/components/NavContainer/NavContainer.js
  src/pages/components/NavContainer/NavContainer.scss
  src/pages/components/NavContainer/SearchBox/Navdata.js
  src/pages/components/NavContainer/SearchBox/SearchBox.js
  src/pages/components/NavContainer/SearchBox/SearchBox.scss
Labels: Status: 리뷰 요청, Status: 수정 완료

#7 [13기 백경민] Add: MainBanner conflict 해결 및 추가 리팩토링
  debug.log
  package-lock.json
  package.json
  public/images/MainBanner_grey.png
  public/images/MainBanner_pink.png
  public/images/MainBanner_purple.png
  public/images/MainBanner_rainbow.png
  src/Routes.js
  src/Styles/reset.scss
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.js
  src/pages/MainPage/components/MainBanner/MainBanner.js
  src/pages/MainPage/components/MainBanner/MainBanner.scss
Labels: Status: 수정 완료

#16 [13기 민경민] 주소 정보 관리 하는 AddressList 컴포넌트 작성
  package.json
  src/pages/MyPage/components/Address/Address.js
  src/pages/MyPage/components/Address/Address.scss
  src/pages/MyPage/components/Address/AddressList.js
  src/pages/MyPage/components/Address/AddressList.scss
  src/pages/MyPage/components/Address/AddressModal.js
  src/pages/MyPage/components/Address/AddressModal.scss
Labels: Status: 리뷰 요청

#17 [13기 백경민] 회원가입 페이지 수정
  src/pages/JoinSteps/JoinStepThree.scss
  src/pages/JoinSteps/JoinStepTwo.js
  src/pages/JoinSteps/JoinStepTwo.scss
Labels: Status: 리뷰 요청

#19 [13기 김한나] Fix: ProductList Nav ,filter.pasing 기능구현
  package-lock.json
  public/images/page_next.png
  public/images/page_nnext.png
  public/images/page_pprev.png
  public/images/page_prev.png
  src/Routes.js
  src/pages/StationeryList/StationeryList.js
  src/pages/components/ProductList/Paging/Paging.js
  src/pages/components/ProductList/Paging/Paging.scss
  src/pages/components/ProductList/Product.js
  src/pages/components/ProductList/ProductList.js
  src/pages/components/ProductList/ProductList.scss
  src/pages/components/ProductListNav/ProductListNav.js
  src/pages/components/ProductListNav/ProductListNav.scss
  src/pages/components/ProductListNav/navdata.js
  src/pages/components/ProductListNav/productsort.js
Labels: Status: Accepted

#20 [13기 김수연] Add: NavContainerLink 연결 및 ListPage Merge 후 conflice 수정
  src/Routes.js
  src/index.js
  src/pages/MyPage/MyPageContainer.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/component/Product/Product.js
  src/pages/ProductList/component/Product/Product.scss
  src/pages/ProductList/component/ProductListNav/ProductListNav.js
  src/pages/ProductList/component/ProductListNav/ProductListNav.scss
  src/pages/ProductList/component/ProductListNav/navdata.js
  src/pages/StationeryList/StationeryList.js
  src/pages/StationeryList/StationeryList.scss
  src/pages/components/NavContainer/MyCurator/components/MyCuratorSlider.js
  src/pages/components/NavContainer/Nav/MenuDropBox/ContentType.js
  src/pages/components/ProductList/ProductList.js
  src/pages/components/ProductList/ProductList.scss
Labels: Status: Accepted, Status: 리뷰 요청

#13 [13기 이지영] Add : product count function && position change
  public/data/product-info.json
  src/Styles/common.scss
  src/Styles/reset.scss
  src/pages/DetailPage/Components/ProductDetail/ProductDetail.js
  src/pages/DetailPage/Components/ProductDetail/ProductDetail.scss
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.js
  src/pages/DetailPage/Components/ProductInfo/ProductInfo.scss
  src/pages/DetailPage/Components/ProductInfo/option/option.js
  src/pages/DetailPage/Components/ProductInfo/option/option.scss
  src/pages/DetailPage/Components/ProductReview/ProductReview.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPage.scss
  src/pages/MyPage/personalInfo/personalInfo.js
  src/pages/MyPage/personalInfo/personalInfo.scss
Labels: Status: 리뷰 요청

#14 [13기 백경민] Add: Cart Page 레이아웃 완성
  README.md
  public/data/cart.json
  src/Routes.js
  src/pages/Cart/AddCart.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
Labels: Status: Accepted
